package easy

import utils.runFunction
import kotlin.time.measureTime

fun main(args: Array<String>) {
    val time = measureTime {
        "anagram".runFunction(true) {
            println(isAnagram("anagram", "nagaram"))
            println(isAnagram("rat", "car"))
        }
    }
    println(time)
}

fun isAnagram(s: String, t: String): Boolean {
    if (s.length != t.length) {
        return false
    }
    return s.toCharArray().sortedArray().contentEquals(t.toCharArray().sortedArray())
//
//            val countS = mutableMapOf<Char, Int>()
//            val countT = mutableMapOf<Char, Int>()
//
//            for (i in s.indices) {
//                countS[s[i]] = countS.getOrDefault(s[i], 0) + 1
//                countT[t[i]] = countT.getOrDefault(t[i], 0) + 1
//            }
//
//            return countS == countT
}

// ═══════════════════════════════════════════════
// 2. GROUP ANAGRAMS (HashMap signature)
// ═══════════════════════════════════════════════

/**
 * Groups lowercase English words by anagram signature.
 * Time: O(n * m), where m = avg word length
 * Space: O(n * m)
 *
 * Uses frequency signature instead of sorting each word.
 *
 * The `groupAnagramsSimplified` function groups words that are anagrams of each other. Here's how it works step by step:
 * 1. **`words.groupBy { ... }`** - Groups the input list of words based on a key generated by the lambda function. Words with the same key end up in the same group.
 * 2. **`it.toCharArray()`** - Converts each word into an array of individual characters.
 * 3. **`.sorted()`** - Sorts the characters alphabetically. This creates a canonical form where anagrams produce identical sorted sequences (e.g., "eat", "tea", "ate" all become ['a', 'e', 't']).
 * 4. **`.joinToString("")`** - Combines the sorted characters back into a single string to use as the grouping key (e.g., "aet").
 * 5. **`.values`** - Extracts just the grouped word lists, discarding the signature keys. This returns a collection of lists where each list contains anagrams.
 * 6. **`.toList()`** - Converts the collection into a standard `List<List<String>>`.
 *
 * **Example**:
 * - Input: `["eat", "tea", "tan", "ate", "nat", "bat"]`
 * - After grouping by signature: `{"aet": ["eat", "tea", "ate"], "ant": ["tan", "nat"], "abt": ["bat"]}`
 * - Final output: `[["eat", "tea", "ate"], ["tan", "nat"], ["bat"]]`
 */
fun groupAnagramsSimplified(words: List<String>): List<List<String>> {
    return words
        .groupBy { it.toCharArray().sorted().joinToString("") }
        .values
        .toList()
}