version: '3'

services:
  backend:
    image: "ahmedvhashem/first-node-app:1.0"
    ports:
      - "8080:8080"
  webserver:
    image: "nginx:alpine"
    ports:
      - "80:80"
  db:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: test-password
    volumes:
      - db-data:/foo

volumes:
  db-data:
