# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

ENV["SLACK_WEBHOOK_URL"] = "https://hooks.slack.com/services/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"

default_platform(:android)

platform :android do
  desc "Debug build"
  lane :buildDebug do
    begin
      gradle(task: "clean assemble", build_type: "Debug")
      on_success("Debug build Succeeded!")
    rescue => exception
      on_error(exception)
    end
  end

  desc "Release build"
  lane :buildRelease do
    begin
      gradle(task: "clean assemble", build_type: "Release")
      on_success("Release build Succeeded!")
    rescue => exception
      on_error(exception)
    end
  end

end

def on_success(success_message)
    slack(
       message: success_message,
       success: true,
       slack_url: ENV["SLACK_WEBHOOK_URL"]
    )
end

def on_error(exception)
    slack(
       message: "Something went wrong! check *Error Info* for more details.",
       success: false,
       slack_url: ENV["SLACK_WEBHOOK_URL"],
       payload: { "Error Info" => exception.to_s }
    )
end
